version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=vehicle_allocation
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
